# Generated by Django 5.2.1 on 2025-12-19 04:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock symbol', max_length=50, unique=True)),
                ('total_buy_qty', models.IntegerField(help_text='Total buy quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Buy price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_buy_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total buy value (calculated: total_buy_qty * buy_price)', max_digits=12)),
                ('total_sell_qty', models.IntegerField(default=0, help_text='Total sell quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sell price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sell_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sell value (calculated: total_sell_qty * sell_price)', max_digits=12)),
                ('balance_qty', models.IntegerField(default=0, help_text='Balance quantity (always saved as 0)')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Acquisition cost (always 0.00)', max_digits=12)),
                ('percent_holding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage holding (always 0.00)', max_digits=5)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current value (always 0.00)', max_digits=12)),
                ('realised_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Realised profit/loss (calculated: sell_price - buy_price)', max_digits=12)),
                ('wk_52_high', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='52 week high price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wk_52_low', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='52 week low price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Trade',
                'verbose_name_plural': 'Stock Trades',
                'ordering': ['-created_at'],
            },
        ),
    ]
