# Generated by Django 5.2.1 on 2025-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrade',
            name='current_portfolio',
            field=models.CharField(blank=True, help_text='Current portfolio name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='date_time_field',
            field=models.CharField(blank=True, help_text="Formatted date time string: 'As on Nov 28, 5025 16:00:27 Hours IST'", max_length=100),
        ),
    ]
