# Generated by Django 6.0 on 2025-12-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocktrade_current_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Portfolio name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.RemoveField(
            model_name='stocktrade',
            name='current_portfolio',
        ),
        migrations.AddField(
            model_name='stocktrade',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='Parent portfolio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.portfolio'),
        ),
    ]
