# Generated by Django 6.0 on 2025-12-24 08:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_portfolio_remove_stocktrade_current_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrade',
            name='ltp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ltp price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
